# Generated by Django 5.2.5 on 2025-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ability_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
